version: "3.8"

services:
    backend:
        build: ./backend
        ports: 
          - "8000:8000"
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        depends_on:
          - "db"

    frontend:
        build: ./frontend
        ports:
          - "3000:3000"
        command: npm start
        stdin_open: true
    db:
        image: postgres:12
        ports: 
          - "5432:5432"
        env_file:
          - db.env
        volumes:
          - ./postgresql:/var/lib/postgresql/data



