# Generated by Django 3.0.5 on 2020-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspec',
            name='Коробка передач',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
