# Generated by Django 3.0.5 on 2020-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0002_carspec_коробка передач'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspec',
            name='Выбросы CO2, г/км',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Высота',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Диаметр цилиндра и ход поршня, мм',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Длина',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Задние тормоза',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Изображение',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Класс автомобиля',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Клиренс',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Количество дверей',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Количество мест',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Количество передач',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Количество цилиндров',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Колёсная база',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Коробка передач',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Максимальная мощность, л.с./кВт при об/мин',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Максимальная скорость, км/ч',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Максимальный крутящий момент, Н*м при об/мин',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Марка топлива',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Название рейтинга',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Объем багажника макс, л',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Объем багажника мин, л',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Объем двигателя, см³',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Объём топливного бака, л',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Оценка безопасности',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Передние тормоза',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Полная масса, кг',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Разгон до 100 км/ч, с',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Размер колёс',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Расположение двигателя',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Расположение цилиндров',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Расход топлива, л город',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Расход топлива, л смешанный',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Расход топлива, л трасса',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Система питания двигателя',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Снаряженная масса, кг',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Ссылка',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Степень сжатия',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Страна марки',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Тип двигателя',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Тип задней подвески',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Тип наддува',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Тип передней подвески',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Тип привода',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Цена',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Число клапанов на цилиндр',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Ширина',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Ширина задней колеи',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Ширина передней колеи',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='Экологический класс',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
