# Generated by Django 3.0.5 on 2020-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0003_auto_20200419_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspec',
            name='Изображение',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Ссылка',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Изображение',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Ссылка',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
