# Generated by Django 3.0.5 on 2020-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0004_auto_20200419_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='Изображение',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Марка',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Модель',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Поколение',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Ссылка',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Тип кузова',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Выбросы CO2, г/км',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Высота',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Диаметр цилиндра и ход поршня, мм',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Длина',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Задние тормоза',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Класс автомобиля',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Клиренс',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Количество дверей',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Количество мест',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Количество передач',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Количество цилиндров',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Колёсная база',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Коробка передач',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Максимальная мощность, л.с./кВт при об/мин',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Максимальная скорость, км/ч',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Максимальный крутящий момент, Н*м при об/мин',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Марка топлива',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Название рейтинга',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Объем багажника макс, л',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Объем багажника мин, л',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Объем двигателя, см³',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Объём топливного бака, л',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Оценка безопасности',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Передние тормоза',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Полная масса, кг',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Разгон до 100 км/ч, с',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Размер колёс',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Расположение двигателя',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Расположение цилиндров',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Расход топлива, л город',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Расход топлива, л смешанный',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Расход топлива, л трасса',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Система питания двигателя',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Снаряженная масса, кг',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Степень сжатия',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Страна марки',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Тип двигателя',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Тип задней подвески',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Тип наддува',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Тип передней подвески',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Тип привода',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Число клапанов на цилиндр',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Ширина',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Ширина задней колеи',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Ширина передней колеи',
        ),
        migrations.RemoveField(
            model_name='carspec',
            name='Экологический класс',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Значение',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(default=1, max_length=50, verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='config',
            field=models.CharField(default=1, max_length=30, verbose_name='Тип кузова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='generation',
            field=models.CharField(default=1, max_length=100, verbose_name='Поколение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(default=1, max_length=100, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carspec',
            name='acceleration',
            field=models.FloatField(blank=True, null=True, verbose_name='Разгон до 100 км/ч, с'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='auto_class',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Класс автомобиля'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='back_suspension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип задней подвески'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='boot_volume_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем багажника макс, л'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='boot_volume_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем багажника мин, л'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='bore_stroke',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Диаметр цилиндра и ход поршня, мм'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='clearance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Клиренс'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='compression_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Степень сжатия'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна марки'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='curb_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Снаряженная масса, кг'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='cylinder_arrangement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Расположение цилиндров'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='cylinder_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество цилиндров'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='door_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество дверей'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='eco_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Экологический класс'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='emissions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выбросы CO2, г/км'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем двигателя, см³'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='engine_location',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Расположение двигателя'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='engine_power_system',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Система питания двигателя'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='engine_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='front_breaks',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Передние тормоза'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='front_suspension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип передней подвески'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='front_track_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина передней колеи'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='fuel_consumption_city',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход топлива, л город'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='fuel_consumption_mixed',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход топлива, л смешанный'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='fuel_consumption_track',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход топлива, л трасса'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='fuel_grade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Марка топлива'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='full_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Полная масса, кг'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='maximum_power',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальная мощность, л.с./кВт при об/мин'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='maximum_torque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальный крутящий момент, Н*м при об/мин'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='name_of_rating',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Название рейтинга'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='number_of_gears',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество передач'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='number_of_valves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число клапанов на цилиндр'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='rear_breaks',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Задние тормоза'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='rear_track_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина задней колеи'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='safety_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка безопасности'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='top_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная скорость, км/ч'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='transmission',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='trunk_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём топливного бака, л'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='type_of_boost',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип наддува'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='type_of_drive',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип привода'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='wheel_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер колёс'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='wheelbase',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колёсная база'),
        ),
        migrations.AddField(
            model_name='carspec',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=11, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
