# Generated by Django 3.0.5 on 2020-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0005_auto_20200419_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
