# Generated by Django 3.0.5 on 2020-05-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0006_auto_20200510_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspec',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='car',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='CarSpec',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
