# Generated by Django 3.0.5 on 2020-05-19 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendedSystem', '0007_auto_20200519_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_name', models.CharField(max_length=100, verbose_name='Поколение')),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=50, verbose_name='Марка')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна марки')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarBody')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarGeneration')),
            ],
        ),
        migrations.CreateModel(
            name='CarModelModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarModelInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_group_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='recomendedSystem.CarModelInstance')),
                ('model2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_model', to='recomendedSystem.CarModelInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Значение')),
                ('car_model_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarModelModification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Значение')),
                ('car_model_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarModelModification')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.ParameterGroup'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarMake')),
            ],
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendedSystem.CarModel'),
        ),
    ]
