# Generated by Django 3.0.5 on 2020-05-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0008_auto_20200519_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelmodification',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='car_model_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='recomendedSystem.CarModelModification'),
        ),
    ]
