# Generated by Django 3.0.5 on 2020-05-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0009_auto_20200520_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelmodification',
            name='car_model_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model_modifications', to='recomendedSystem.CarModelInstance'),
        ),
    ]
