# Generated by Django 3.0.5 on 2020-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0011_auto_20200521_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodelinstance',
            name='auto_class',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Класс автомобиля'),
        ),
        migrations.AddField(
            model_name='carmodelinstance',
            name='door_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество дверей'),
        ),
        migrations.AddField(
            model_name='carmodelinstance',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
    ]
