# Generated by Django 3.0.6 on 2020-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendedSystem', '0012_auto_20200522_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна марки'),
        ),
    ]
